export const bancos = [
    "Banco do Brasil",
    "Banco do Nordeste",
    "Banco Santander Banespa",
    "Banco J. Safra",
    "Banco Inter",
    "Caixa Econômica Federal",
    "American Express Bank",
    "Banco Itaú BBA",
    "Banco Bonsucesso",
    "Bradesco",
    "Next",
    "Nubank",
    "Banco BMG",
    "Itau",
    "Banco Santander",
    "Banco Santander Brasil",
    "Unibanco",
    "Banco Safra",
    "Itaú Holding Financeira",
       
    ]