export const codesAndFlags = [
  {
    name: "Brazil",
    dial_code: "+55",
    code: "BR",
    image: "/images/brasil-flag.png" 
  },
  {
    name: "Argentina",
    dial_code: "+54",
    code: "AR",
    image: "/images/argentina.png",
  },
  {
    name: "Canada",
    dial_code: "+1",
    code: "CA",
    image: "/images/canada.png",
  },
  {
    name: "Chile",
    dial_code: "+56",
    code: "CL",
    image: "/images/chile.png",
  },
  {
    name: "China",
    dial_code: "+86",
    code: "CN",
    image: "/images/china.png",
  },
  {
    name: "Colombia",
    dial_code: "+57",
    code: "CO",
    image: "/images/colombia.png",
  },
  {
    name: "Costa Rica",
    dial_code: "+506",
    code: "CR",
    image: "/images/costa-rica.png",
  },
  {
    name: "El Salvador",
    dial_code: "+503",
    code: "SV",
    image: "/images/El-Salvador.png",
  },
  {
    name: "France",
    dial_code: "+33",
    code: "FR",
    image: "/images/france.png",
  },
  {
    name: "Germany",
    dial_code: "+49",
    code: "DE",
    image: "/images/germany.png",
  },
  {
    name: "India",
    dial_code: "+91",
    code: "IN",
    image: "/images/India.png",
  },
  {
    name: "Italy",
    dial_code: "+39",
    code: "IT",
    image: "/images/Italy.png",
  },
  {
    name: "Japan",
    dial_code: "+81",
    code: "JP",
    image: "/images/Japan.png",
  },
  {
    name: "Mexico",
    dial_code: "+52",
    code: "MX",
    image: "/images/Mexico.png",
  },
  {
    name: "Paraguay",
    dial_code: "+595",
    code: "PY",
    image: "/images/Paraguay.png",
  },
  {
    name: "Peru",
    dial_code: "+51",
    code: "PE",
    image: "/images/Peru.png",
  },
  {
    name: "Portugal",
    dial_code: "+351",
    code: "PT",
    image: "/images/Portugal.png",
  },
  {
    name: "Spain",
    dial_code: "+34",
    code: "ES",
    image: "/images/Spain.png",
  },
  {
    name: "Türkiye",
    dial_code: "+90",
    code: "TR",
    image: "/images/turquia.png",
  },
  {
    name: "Ukraine",
    dial_code: "+380",
    code: "UA",
    image: "/images/Ukraine.png",
  },
  {
    name: "United Kingdom",
    dial_code: "+44",
    code: "GB",
    image: "/images/United-Kingdom.png",
  },
  {
    name: "United States",
    dial_code: "+1",
    code: "US",
    image: "/images/United-States.png",
  },
  {
    name: "Uruguay",
    dial_code: "+598",
    code: "UY",
    image: "/images/Uruguay.png",
  },
  {
    name: "Russia",
    dial_code: "+7",
    code: "RU",
    image: "/images/Russia.png",
  },
  {
    name: "Venezuela, Bolivarian Republic of",
    dial_code: "+58",
    code: "VE",
    image: "/images/Venezuela.png",
  },
];
